import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('stock_data.db')
cursor = conn.cursor()

# Create the 'INCOME' table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS INCOME (
        ticker TEXT,
        date DATE,
        "Tax_Effect_Of_Unusual_Items" REAL,
        "Tax_Rate_For_Calcs" REAL,
        "Normalized_EBITDA" REAL,
        "Total_Unusual_Items" REAL,
        "Total_Unusual_Items_Excluding_Goodwill" REAL,
        "Net_Income_From_Continuing_Operation_Net_Minority_Interest" REAL,
        "Reconciled_Depreciation" REAL,
        "Reconciled_Cost_Of_Revenue" REAL,
        "EBIT" REAL,
        "Net_Interest_Income" REAL,
        "Interest_Expense" REAL,
        "Interest_Income" REAL,
        "Normalized_Income" REAL,
        "Net_Income_From_Continuing_And_Discontinued_Operation" REAL,
        "Total_Expenses" REAL,
        "Total_Operating_Income_As_Reported" REAL,
        "Diluted_Average_Shares" REAL,
        "Basic_Average_Shares" REAL,
        "Diluted_EPS" REAL,
        "Basic_EPS" REAL,
        "Diluted_NI_Availto_Com_Stockholders" REAL,
        "Net_Income_Common_Stockholders" REAL,
        "Net_Income" REAL,
        "Net_Income_Including_Noncontrolling_Interests" REAL,
        "Net_Income_Continuous_Operations" REAL,
        "Tax_Provision" REAL,
        "Pretax_Income" REAL,
        "Other_Income_Expense" REAL,
        "Other_Non_Operating_Income_Expenses" REAL,
        "Special_Income_Charges" REAL,
        "Write_Off" REAL,
        "Gain_On_Sale_Of_Security" REAL,
        "Net_Non_Operating_Interest_Income_Expense" REAL,
        "Interest_Expense_Non_Operating" REAL,
        "Interest_Income_Non_Operating" REAL,
        "Operating_Income" REAL,
        "Operating_Expense" REAL,
        "Research_And_Development" REAL,
        "Selling_General_And_Administration" REAL,
        "Selling_And_Marketing_Expense" REAL,
        "General_And_Administrative_Expense" REAL,
        "Other_Gand_A" REAL,
        "Gross_Profit" REAL,
        "Cost_Of_Revenue" REAL,
        "Total_Revenue" REAL,
        "Operating_Revenue" REAL,
        PRIMARY KEY (ticker, date)
    )
''')

print("INCOME table created.")



# Create the 'BALANCE' table if not exists
cursor.execute('''
    CREATE TABLE IF NOT EXISTS BALANCE (
    ticker TEXT,
    date DATE,
    "Ordinary_Shares_Number" REAL,
    "Share_Issued" REAL,
    "Net_Debt" REAL,
    "Total_Debt" REAL,
    "Tangible_Book_Value" REAL,
    "Invested_Capital" REAL,
    "Working_Capital" REAL,
    "Net_Tangible_Assets" REAL,
    "Capital_Lease_Obligations" REAL,
    "Common_Stock_Equity" REAL,
    "Total_Capitalization" REAL,
    "Total_Equity_Gross_Minority_Interest" REAL,
    "Stockholders_Equity" REAL,
    "Gains_Losses_Not_Affecting_Retained_Earnings" REAL,
    "Other_Equity_Adjustments" REAL,
    "Retained_Earnings" REAL,
    "Capital_Stock" REAL,
    "Common_Stock" REAL,
    "Total_Liabilities_Net_Minority_Interest" REAL,
    "Total_Non_Current_Liabilities_Net_Minority_Interest" REAL,
    "Other_Non_Current_Liabilities" REAL,
    "Tradeand_Other_Payables_Non_Current" REAL,
    "Non_Current_Deferred_Liabilities" REAL,
    "Non_Current_Deferred_Revenue" REAL,
    "Non_Current_Deferred_Taxes_Liabilities" REAL,
    "Long_Term_Debt_And_Capital_Lease_Obligation" REAL,
    "Long_Term_Capital_Lease_Obligation" REAL,
    "Long_Term_Debt" REAL,
    "Current_Liabilities" REAL,
    "Other_Current_Liabilities" REAL,
    "Current_Deferred_Liabilities" REAL,
    "Current_Deferred_Revenue" REAL,
    "Current_Debt_And_Capital_Lease_Obligation" REAL,
    "Current_Debt" REAL,
    "Pensionand_Other_Post_Retirement_Benefit_Plans_Current" REAL,
    "Payables_And_Accrued_Expenses" REAL,
    "Payables" REAL,
    "Total_Tax_Payable" REAL,
    "Income_Tax_Payable" REAL,
    "Accounts_Payable" REAL,
    "Total_Assets" REAL,
    "Total_Non_Current_Assets" REAL,
    "Other_Non_Current_Assets" REAL,
    "Investments_And_Advances" REAL,
    "Long_Term_Equity_Investment" REAL,
    "Goodwill_And_Other_Intangible_Assets" REAL,
    "Other_Intangible_Assets" REAL,
    "Goodwill" REAL,
    "Net_PPE" REAL,
    "Accumulated_Depreciation" REAL,
    "Gross_PPE" REAL,
    "Leases" REAL,
    "Other_Properties" REAL,
    "Machinery_Furniture_Equipment" REAL,
    "Buildings_And_Improvements" REAL,
    "Land_And_Improvements" REAL,
    "Properties" REAL,
    "Current_Assets" REAL,
    "Other_Current_Assets" REAL,
    "Hedging_Assets_Current" REAL,
    "Inventory" REAL,
    "Finished_Goods" REAL,
    "Work_In_Process" REAL,
    "Raw_Materials" REAL,
    "Receivables" REAL,
    "Accounts_Receivable" REAL,
    "Allowance_For_Doubtful_Accounts_Receivable" REAL,
    "Gross_Accounts_Receivable" REAL,
    "Cash_Cash_Equivalents_And_Short_Term_Investments" REAL,
    "Other_Short_Term_Investments" REAL,
    "Cash_And_Cash_Equivalents" REAL,
    "Cash_Equivalents" REAL,
    "Cash_Financial" REAL,
    PRIMARY KEY (ticker, date)
)

''')

print("BALANCE table created.")


# Create the 'CASHFLOW' table if not exists
cursor.execute('''
    CREATE TABLE IF NOT EXISTS CASH_FLOW (
    ticker TEXT,
    date DATE,
    "Free_Cash_Flow" REAL,
    "Repurchase_Of_Capital_Stock" REAL,
    "Repayment_Of_Debt" REAL,
    "Issuance_Of_Debt" REAL,
    "Issuance_Of_Capital_Stock" REAL,
    "Capital_Expenditure" REAL,
    "End_Cash_Position" REAL,
    "Beginning_Cash_Position" REAL,
    "Effect_Of_Exchange_Rate_Changes" REAL,
    "Changes_In_Cash" REAL,
    "Financing_Cash_Flow" REAL,
    "Cash_Flow_From_Continuing_Financing_Activities" REAL,
    "Net_Other_Financing_Charges" REAL,
    "Cash_Dividends_Paid" REAL,
    "Common_Stock_Dividend_Paid" REAL,
    "Net_Common_Stock_Issuance" REAL,
    "Common_Stock_Payments" REAL,
    "Common_Stock_Issuance" REAL,
    "Net_Issuance_Payments_Of_Debt" REAL,
    "Net_Short_Term_Debt_Issuance" REAL,
    "Net_Long_Term_Debt_Issuance" REAL,
    "Long_Term_Debt_Payments" REAL,
    "Long_Term_Debt_Issuance" REAL,
    "Investing_Cash_Flow" REAL,
    "Cash_Flow_From_Continuing_Investing_Activities" REAL,
    "Net_Other_Investing_Changes" REAL,
    "Net_Investment_Purchase_And_Sale" REAL,
    "Sale_Of_Investment" REAL,
    "Purchase_Of_Investment" REAL,
    "Net_Business_Purchase_And_Sale" REAL,
    "Purchase_Of_Business" REAL,
    "Net_PPE_Purchase_And_Sale" REAL,
    "Purchase_Of_PPE" REAL,
    "Operating_Cash_Flow" REAL,
    "Cash_Flow_From_Continuing_Operating_Activities" REAL,
    "Change_In_Working_Capital" REAL,
    "Change_In_Other_Working_Capital" REAL,
    "Change_In_Other_Current_Liabilities" REAL,
    "Change_In_Other_Current_Assets" REAL,
    "Change_In_Payables_And_Accrued_Expense" REAL,
    "Change_In_Payable" REAL,
    "Change_In_Account_Payable" REAL,
    "Change_In_Inventory" REAL,
    "Change_In_Receivables" REAL,
    "Changes_In_Account_Receivables" REAL,
    "Stock_Based_Compensation" REAL,
    "Deferred_Tax" REAL,
    "Deferred_Income_Tax" REAL,
    "Depreciation_Amortization_Depletion" REAL,
    "Depreciation_And_Amortization" REAL,
    "Depreciation" REAL,
    "Operating_Gains_Losses" REAL,
    "Gain_Loss_On_Investment_Securities" REAL,
    "Net_Income_From_Continuing_Operations" REAL,
    PRIMARY KEY (ticker, date)
)

''')


# Commit changes and close the connection
conn.commit()
conn.close()

print("CASH-FLOW table created.")
